apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsu.fullname" . }}-console
  labels:
    {{- include "jitsu.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: {{ .Values.console.strategyType }}
  selector:
    matchLabels:
      {{- include "jitsu.selectorLabels" . | nindent 6 }}
      app: console
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jitsu.selectorLabels" . | nindent 8 }}
        app: console
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jitsu.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.console.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-console
          securityContext:
            {{- toYaml .Values.console.securityContext | nindent 12 }}
          image: "{{ .Values.console.image.repository }}:{{ .Values.console.image.tag }}"
          env:    
            {{- range $key, $val := .Values.console.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
            {{- range $key, $val := .Values.secret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Chart.Name }}-secret
                  key: {{ $key }}
            {{- end}}
          imagePullPolicy: {{ .Values.console.image.pullPolicy }}
          ports:
            - name: console
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: console
          readinessProbe:
            httpGet:
              path: /
              port: console
          resources:
            {{- toYaml .Values.console.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}